FARTICLE.SRVPGM: FARTICLE.ILESRVPGM ART300.MODULE ART301.MODULE FFAMILLY.SRVPGM
FARTICLEAPI.SRVPGM: FARTICLEAPI.ILESRVPGM ART400.MODULE
FPARAMETER.SRVPGM: FPARAMETER.ILESRVPGM PAR300.MODULE
LOG.SRVPGM: LOG.ILESRVPGM LOG300.MODULE