/**
 * articleService.ts
 * ─────────────────────────────────────────────────────────────────────────────
 * SAMCO Article Management — IBM i IWS REST API Client
 *
 * Consumes the FARTICLEAPI service program exposed via IBM i Integrated
 * Web Services (IWS). All endpoints map 1-to-1 to RPG procedures in ART400.
 *
 * Base URL is read from VITE_API_BASE_URL env var (set per environment).
 * Example .env.local:
 *   VITE_API_BASE_URL=http://my-ibmi:10001/web/services
 *
 * Endpoints:
 *   GET    /articles          → listAllArticles()
 *   GET    /articles/:id      → getArticle(id)
 *   POST   /articles          → createArticle(data)
 *   PUT    /articles/:id      → updateArticle(id, data)
 *   DELETE /articles/:id      → deleteArticle(id)
 *   GET    /articles/:id/info → getArticleInfo(id)
 * ─────────────────────────────────────────────────────────────────────────────
 */

// ─── Types ────────────────────────────────────────────────────────────────────

/** Maps to RPG Dcl-Ds ArticleItem in ART400 (field names via *DCLCASE) */
export interface Article {
  id: string;
  description: string;
  familyCode: string;
  familyDesc: string;
  vatCode: string;
  vatRate: number;
  salePrice: number;
  warehousePrice: number;
  stock: number;
  minimumQuantity: number;
  deleted: string;
  creationDate: string;    // ISO date string "YYYY-MM-DD"
  lastModified: string;    // ISO timestamp string
  lastModifiedBy: string;
}

/** Maps to RPG Dcl-Ds ArticleInput — used for POST and PUT request bodies */
export interface ArticleInput {
  id?: string;
  description: string;
  familyCode: string;
  vatCode: string;
  salePrice: number;
  warehousePrice: number;
  stock: number;
  minimumQuantity: number;
}

/** Maps to RPG Dcl-Ds ArticleListResponse */
export interface ArticleListResponse {
  success: boolean;
  message: string;
  totalRecords: number;
  articleCount: number;
  articleData: Article[];
}

/** Maps to RPG Dcl-Ds ArticleResponse (single article) */
export interface ArticleResponse {
  success: boolean;
  message: string;
  article: Article;
}

/** Maps to RPG Dcl-Ds ApiResponse (create/update/delete) */
export interface ApiResponse {
  success: boolean;
  message: string;
  id: string;
}

/** Maps to RPG Dcl-Ds ArticleInfoResponse */
export interface ArticleInfoResponse {
  success: boolean;
  message: string;
  id: string;
  information: string;
}

// ─── Configuration ────────────────────────────────────────────────────────────

const BASE_URL =
  (import.meta as Record<string, Record<string, string>>).env
    ?.VITE_API_BASE_URL ?? 'http://localhost:10001/web/services';

const ARTICLES_URL = `${BASE_URL}/articles`;

// ─── Internal fetch helper ────────────────────────────────────────────────────

/**
 * Generic fetch wrapper: adds Content-Type, handles HTTP errors,
 * and returns parsed JSON.  Throws an Error with a descriptive message
 * on any non-2xx HTTP response.
 */
async function apiFetch<T>(
  url: string,
  options?: RequestInit
): Promise<T> {
  const defaultHeaders: HeadersInit = {
    'Content-Type': 'application/json',
    Accept: 'application/json',
  };

  const response = await fetch(url, {
    ...options,
    headers: {
      ...defaultHeaders,
      ...options?.headers,
    },
  });

  if (!response.ok) {
    // Try to extract a meaningful message from the IWS error body
    let errorMessage = `HTTP ${response.status}: ${response.statusText}`;
    try {
      const errorBody = await response.json() as { message?: string };
      if (errorBody.message) errorMessage = errorBody.message;
    } catch {
      // ignore JSON parse error on error response
    }
    throw new Error(errorMessage);
  }

  return response.json() as Promise<T>;
}

// ─── API Functions ────────────────────────────────────────────────────────────

/**
 * GET /articles
 *
 * Retrieves all active (non-deleted) articles with family and VAT details.
 * Maps to RPG procedure LISTALLARTICLES in FARTICLEAPI.
 *
 * @returns ArticleListResponse containing the articleData array
 */
export async function listAllArticles(): Promise<ArticleListResponse> {
  return apiFetch<ArticleListResponse>(ARTICLES_URL);
}

/**
 * GET /articles/:id
 *
 * Retrieves a single article by its 6-character ID.
 * Maps to RPG procedure GETARTICLE in FARTICLEAPI.
 *
 * @param id  Article ID (6 chars, e.g. "000001")
 * @returns   ArticleResponse with the article details
 */
export async function getArticle(id: string): Promise<ArticleResponse> {
  return apiFetch<ArticleResponse>(`${ARTICLES_URL}/${encodeURIComponent(id)}`);
}

/**
 * POST /articles
 *
 * Creates a new article. The ID is auto-generated by the RPG procedure.
 * Maps to RPG procedure CREATEARTICLE in FARTICLEAPI.
 *
 * @param data  ArticleInput object (description is mandatory)
 * @returns     ApiResponse with the generated article ID on success
 */
export async function createArticle(data: ArticleInput): Promise<ApiResponse> {
  return apiFetch<ApiResponse>(ARTICLES_URL, {
    method: 'POST',
    body: JSON.stringify(data),
  });
}

/**
 * PUT /articles/:id
 *
 * Updates an existing article.
 * Maps to RPG procedure UPDATEARTICLE in FARTICLEAPI.
 *
 * @param id    Article ID (6 chars)
 * @param data  ArticleInput with updated values
 * @returns     ApiResponse
 */
export async function updateArticle(
  id: string,
  data: ArticleInput
): Promise<ApiResponse> {
  return apiFetch<ApiResponse>(`${ARTICLES_URL}/${encodeURIComponent(id)}`, {
    method: 'PUT',
    body: JSON.stringify(data),
  });
}

/**
 * DELETE /articles/:id
 *
 * Soft-deletes an article (sets ARDEL='X' on ARTICLE table).
 * Mirrors the green-screen ART200 Opt 4=Delete behaviour.
 * Maps to RPG procedure DELETEARTICLE in FARTICLEAPI.
 *
 * @param id  Article ID (6 chars)
 * @returns   ApiResponse
 */
export async function deleteArticle(id: string): Promise<ApiResponse> {
  return apiFetch<ApiResponse>(`${ARTICLES_URL}/${encodeURIComponent(id)}`, {
    method: 'DELETE',
  });
}

/**
 * GET /articles/:id/info
 *
 * Retrieves the long-form information text for an article.
 * Mirrors the green-screen ART200 FMT03 panel (Opt 3=Info).
 * Maps to RPG procedure GETARTICLEINFO in FARTICLEAPI.
 *
 * @param id  Article ID (6 chars)
 * @returns   ArticleInfoResponse with the information text
 */
export async function getArticleInfo(id: string): Promise<ArticleInfoResponse> {
  return apiFetch<ArticleInfoResponse>(
    `${ARTICLES_URL}/${encodeURIComponent(id)}/info`
  );
}
